version: "3.9"
services:

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

  django:
    working_dir: /app
    build: .
    volumes:
      - .:/app
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  celery:
    working_dir: /app
    command: celery -A insta_api worker --loglevel=info -E
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
      - django
    restart: on-failure
    environment:
      - DJANGO_SETTINGS_MODULE=insta_api.settings

  beat:
    working_dir: /app
    command: celery -A insta_api beat
    build: .
    volumes:
      - .:/app
    depends_on:
      - celery
    restart: on-failure
    environment:
      - DJANGO_SETTINGS_MODULE=insta_api.settings
