# Generated by Django 4.0.5 on 2022-06-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_text_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Текст для поста'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='niche',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
