# Generated by Django 4.0.5 on 2022-07-05 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_alter_text_content_alter_text_niche_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Текст'},
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='instagram.content', verbose_name='Контент')),
                ('niche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='instagram.niche', verbose_name='Ниша')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='instagram.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображений',
            },
        ),
    ]
