# Generated by Django 4.0.5 on 2022-07-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_alter_text_options_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='niche',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка'),
        )
    ]
