# Generated by Django 4.0.5 on 2022-07-07 17:23

from django.db import migrations, models
import instagram.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_content_icon_niche_icon_rubric_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=instagram.utils.icon_file_path, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='niche',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=instagram.utils.icon_file_path, verbose_name='Иконка'),
        ),
    ]
