# Generated by Django 4.0.5 on 2022-07-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_alter_content_icon_alter_niche_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='instagram.content', verbose_name='Контент')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='instagram.postimage', verbose_name='Фото')),
                ('niche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='instagram.niche', verbose_name='Ниша')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='instagram.rubric', verbose_name='Рубрика')),
                ('text', models.ManyToManyField(null=True, related_name='posts', to='instagram.text', verbose_name='Текст')),
            ],
        ),
    ]
