# Generated by Django 4.0.5 on 2022-07-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
